name: Deploy Node.js Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Zip Node Project
      run: zip -r node-backend.zip . -x "node_modules/*" ".env"

    - name: Copy Files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: node-backend.zip
        target: /home/ubuntu/

    - name: SSH and Deploy Node App
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo apt update
          sudo apt install unzip -y

          # Unzip into temp folder
          mkdir -p ~/node-app-temp
          unzip -o ~/node-backend.zip -d ~/node-app-temp

          # Create or preserve .env
          if [ -f ~/node-app/.env ]; then
            cp ~/node-app/.env ~/node-app-temp/.env
          else
            echo "${{ secrets.ENV_FILE }}" > ~/node-app-temp/.env
          fi

          # Replace old app with new version
          rm -rf ~/node-app
          mv ~/node-app-temp ~/node-app

          cd ~/node-app
          npm install

          # Ensure PM2 is installed
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          pm2 delete server || true
          pm2 start index.js --name "server"
          pm2 startup systemd -u ubuntu --hp /home/ubuntu
          pm2 save
