const { database } = require('firebase-admin');
const sequelize = require('../config/db');
const {DataTypes}= require('sequelize');

const Store = sequelize.define('Store',{
  id:{
    type:DataTypes.INTEGER,
    primaryKey:true,
    allowNull:false
  },
  store_name:{
    type:DataTypes.STRING,
    allowNull:false
  },
  store_cover_image:{
    type:DataTypes.TEXT('long'),
    allowNull:false
  },
  status:{
    type:DataTypes.INTEGER,
    allowNull:false
  },
  rating:{
    type:DataTypes.FLOAT,
    allowNull:true
  },
  c_license_code:{
    type:DataTypes.TEXT,
    allowNull:false
  },
  mobile:{
    type:DataTypes.BIGINT,
    allowNull:false
  },
  slogan:{
    type:DataTypes.TEXT,
    allowNull:false,
  },
  slogan_subtitle:{
    type:DataTypes.TEXT,
    allowNull:true
  },
  s_open_time:{
    type:DataTypes.TIME,
    allowNull:false
  },
  s_close_time:{
    type:DataTypes.TIME,
    allowNull:false
  },
  s_pickup_status:{
    type:DataTypes.INTEGER,
    allowNull:true
  },
  tags:{
    type:DataTypes.ARRAY,
    allowNull:false
  },
  short_desc:{
    type:DataTypes.TEXT,
    allowNull:false
  },
  cancel_policy:{
    type:DataTypes.TEXT,
    allowNull:false
  },
  s_type:{
    type:DataTypes.TEXT,
    allowNull:false
  },
  full_address:{
    type:DataTypes.TEXT,
    allowNull:false
  },
  pincode:{
    type:DataTypes.INTEGER,
    allowNull:false
  },
  select_zone:{
    type:DataTypes.TEXT,
    allowNull:true,
  },
  latitude:{
    type:DataTypes.TEXT,
    allowNull:false,
  },
  longitude:{
    type:DataTypes.TEXT,
    allowNull:false,
  },
  service_charge_type:{
    type:DataTypes.ENUM('Fixed Charges','Dynamic Charges'),
    allowNull:false,
  },
  s_charge:{
    type:DataTypes.FLOAT,
    allowNull:false,
  },
  min_order_price:{
    type:DataTypes.FLOAT,
    allowNull:false,
  },
  commission_rate:{
    type:DataTypes.TEXT,
    allowNull:true
  }
})